name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
        
  test-build-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    - run: echo "Composer dependencies have been installed"
    - run: bin/phpunit
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gamzeunal95/my-symfony-app:latest

    - name: Push Docker Image to Docker Hub
      run: docker push gamzeunal95/my-symfony-app:latest
