name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: PHPUnit tests
      uses: php-actions/phpunit@v3
      with:
        configuration: "bin/phpunit"
        memory_limit: "256M"
        
  buildandpush:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gamzeunal95/my-symfony-app:latest

    - name: Push Docker Image to Docker Hub
      run: docker push gamzeunal95/my-symfony-app:latest
